language: node_js
install: npm install
script: rm .gitignore
deploy:
    provider: pages
    cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: main
    target_branch: gh-pages
