language: node_js
install: npm ci
script: rm .gitignore
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: main
    target_branch: gh-pages
