language: node_js
install:
    - cd $TRAVIS_BUILD_DIR
    - npm install
scrpit: npm --version
deploy:
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: false
    local_dir: $TRAVIS_BUILD_DIR
    on:
        branch: main
    target_branch: gh-pages
