language: node_js
install:
    - cd $TRAVIS_BUILD_DIR
    - npm install
scrpit: npm --version
before_deploy:
    - mkdir ../deploy-dir
    - cp -r ./node_modules ../deploy-dir
    - cp ./app.js ../deploy-dir
    - cp ./assets ../deploy-dir
    - cp ./LICENSE ../deploy-dir
    - cp ./index.html ../deploy-dir
    - ls -R ../deploy-dir
deploy:
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: false
    local_dir: ../deploy-dir
    on:
        branch: main
    target_branch: gh-pages
